### PR TITLE
Fix VS crash

### PR DESCRIPTION
**Pull request by tldrlol**
From my experiments, this seems to fix the Exception -> Crash issue.

Unlike what is stated here: https://msdn.microsoft.com/en-us/library/dd821035.aspx#Anchor_5, from what I can gather, the public methods are *NOT* async safe.

There still seem to be issues with cache invalidation, adornments don't always disappear. I don't know whether they are related to what I have provided here.

I'm putting this pull request up as an example of a fix. *NOT* as the proper way of addressing this issue.

Ideally I would remove the use of `SimpleTagger` altogether. Especially since there seems to be overlap between the caching done in this subclass and the capabilities `SimpleTagger` should provide.

### CODE REVIEW

**Comment by jindraivanek** [comment]
I am able to reliably crash it:
codelens2

(Crashed on pressed Enter)

**Comment by realvictorprm** [comment]
Bug found somewhere else. Thank you all for your effort!

**Comment by tldrlol** [comment]
What was it?

**Comment by realvictorprm** [comment]
Hey ;) I meanwhile must tell that the bug still is *not solved*. Unfortunately I was be to reproduce it further so there isn't any solution yer I could tell you.

**Pull request closed without merging**
